// Plain string tables, safe to import from server code (OG images, metadata)
export type { Lang } from "@/shared/lang";
import type { Lang } from "@/shared/lang";

export function t(lang: Lang) {
  return STRINGS[lang];
}

const ms = {
  badge: "🇲🇾 Game mamak · 90 saat",
  tagline: "Satu shift jadi anne mamak. Dengar order, bancuh, hantar.",
  steps3: ["👂 Dengar order", "🫗 Bancuh", "🪑 Hantar"],
  start: "▶ Mula shift",
  howTo: "Cara main & kamus mamak",
  howToItems: [
    "☕ 4 langkah: cawan (panas/ais) → serbuk → susu → gula.",
    "🥛 O = tak letak susu · C = susu cair.",
    "🍬 Kurang = kurang manis · Kosong = tak letak gula.",
    "👨‍👩‍👧 Satu meja boleh order banyak air. Hantar satu-satu.",
    "🤔 Lupa? Tanya balik maksimum 2 kali. Pelanggan makin geram!",
    "🍵 Teh tarik = panas + teh + susu + biasa.",
  ],
  yourBest: "🏆 Rekod kau:",
  challenge: (amount: string, title: string) => `Kawan kau kutip ${amount} (${title}). Boleh lawan?`,
  loading: "Buka kedai...",
  shiftOver: "Shift habis!",
  stats: { served: "Hantar", wrong: "Salah", walkouts: "Lari", streak: "Streak" },
  newRecord: "Rekod baru!",
  namePlaceholder: "Nama kau",
  save: "Simpan",
  nameTooShort: "Nama minimum 2 huruf",
  zeroScore: "Hantar sekurang-kurangnya satu air untuk masuk papan juara",
  savedRank: (n: number) => `Kau nombor ${n} minggu ni!`,
  savedRankToday: (n: number) => `Kau nombor ${n} hari ni!`,
  saved: "Skor disimpan!",
  saveFailed: "Tak dapat simpan",
  challengeFriends: "Cabar kawan",
  playAgain: "▶ Main lagi",
  copied: "Link dah copy. Paste kat Threads!",
  shareText: (amount: string, emoji: string, title: string) => `Aku kutip ${amount} satu shift kat Anne Maju ${emoji} (${title}). Kau boleh lawan?`,
  board: "🏆 Papan Juara",
  week: "Minggu ni",
  all: "Semua",
  boardLoading: "Loading...",
  boardEmpty: "Belum ada juara. Jadi yang pertama!",
  rotate: "Pusingkan phone",
  rotateSub: "Game ni main landscape",
  mute: "Tutup bunyi",
  unmute: "Buka bunyi",
  discard: "Buang air",
  steps: { temp: "Cawan", base: "Serbuk", milk: "Susu", sugar: "Gula" },
  values: {
    panas: "Panas",
    ais: "Ais",
    teh: "Teh",
    kopi: "Kopi",
    milo: "Milo",
    nescafe: "Nescafe",
    susu: "Susu",
    c: "C",
    o: "O",
    biasa: "Biasa",
    kurang: "Kurang",
    kosong: "Kosong",
  } as Record<string, string>,
  labels: {
    panas: "PANAS",
    ais: "AIS",
    teh: "TEH",
    kopi: "KOPI",
    milo: "MILO",
    nescafe: "NESCAFE",
    susu: "SUSU",
    c: "C",
    o: "O",
    biasa: "BIASA",
    kurang: "KURANG",
    kosong: "KOSONG",
  } as Record<string, string>,
  ready: "SIAP! TAP PELANGGAN",
  serveHere: "Hantar",
  askAgain: (left: number) => `Lupa? ${left}x`,
  noMoreAsks: "Dah 2 kali",
  annoyedAsk: "Haih, dengar betul-betul!",
  refusedAsk: "Dah dua kali cakap!",
  ranks: ["Budak Baru Masuk Kerja", "Pembancuh Amatur", "Anne Senior", "Tauke Mamak", "Legenda Tarik 24 Jam"],
  happy: ["Terbaik boss!", "Power la anne!", "Ngam!", "Sedap, terima kasih!", "Ini baru betul!"],
  wrong: ["Aiyo, bukan ini saya order la!", "Eh boss, salah ni!", "Saya cakap lain la anne...", "Ini air siapa punya?", "Haih, tak dengar ke?"],
  leave: ["Lama sangat, blah dulu!", "Tak apa la, pergi kedai sebelah.", "Order pun tak ambil..."],
  calls: ["Anne", "Boss", "Macha", "Bang", "Adik", "Thambi"],
  ends: ["!", " ya!", ", cepat sikit!", " lah!", ", terima kasih!"],
  numbers: ["", "satu", "dua", "tiga", "empat"],
  sugarKurang: "Kurang Manis",
  sugarKosong: "Kosong",
  // Pause
  paused: "Rehat jap",
  pause: "Rehat",
  resume: "▶ Sambung",
  restart: "↻ Mula semula",
  quit: "← Keluar ke Kuala Lepak",
  language: "Bahasa",
  sound: "Bunyi",
  // Tutorial
  practice: "Latihan",
  tutorialTitle: "Latihan dulu!",
  tutorialIntro: "Pelanggan pertama kau. Takde timer, ikut je arahan.",
  hintStep: (want: string, label: string) => `Pelanggan nak ${want} → tap ${label}`,
  hintServe: "Siap! Tap pelanggan untuk hantar 👉",
  hintWrongCup: "Tak sama dengan order. Tekan 🗑️ dan cuba lagi",
  tutorialDoneTitle: "Terbaik! 🎉",
  tutorialDoneBody: "Sekarang shift sebenar: 90 saat, ramai pelanggan, ada yang datang berkumpulan.",
  startReal: "▶ Mula shift sebenar",
  skipTutorial: "Langkau latihan",
  // Order slip
  slip: "📝 Slip",
  slipHint: "Tap order untuk tulis dalam slip",
  slipTable: (n: number) => `Meja ${n}`,
  // Wrong drink
  explain: (parts: string[]) => `Nak ${parts.join(", ")}!`,
  notThis: (want: string, got: string) => `${want}, bukan ${got}`,
  fieldWords: { panas: "panas", ais: "ais", teh: "teh", kopi: "kopi", milo: "milo", nescafe: "nescafe", susu: "susu", c: "C", o: "O", biasa: "manis biasa", kurang: "kurang manis", kosong: "kosong" } as Record<string, string>,
  // Combo
  combo: (n: number) => (n >= 10 ? `🔥 x${n} Legenda!` : n >= 5 ? `🔥 x${n} Steady!` : `🔥 x${n} Power!`),
  // Breakdown
  sales: "Jualan",
  tips: "Tip",
  wasted: "Rugi",
  nextRank: (amount: string, title: string) => `${amount} lagi untuk jadi ${title}`,
  topRank: "Kau dah sampai rank paling tinggi! 👑",
  // Unlocks
  unlockedNew: "🔓 Baru dibuka:",
  unlockNames: { nescafe: "Nescafe & gula kosong", c: "Susu C (susu cair)" } as Record<string, string>,
  nextUnlock: (amount: string, name: string) => `Kutip ${amount} lagi (semua shift) untuk buka ${name}`,
  // Outfits
  outfitTitle: "Gaya Anne",
  outfitNew: "👕 Gaya baru dibuka!",
  // Daily
  dailyStart: "📅 Shift Hari Ini",
  dailySub: "Pelanggan sama untuk semua orang. Siapa paling laju?",
  today: "Hari ni",
  dailyBadge: "📅 Shift hari ini",
};

type Strings = typeof ms;

const en: Strings = {
  badge: "🇲🇾 Mamak game · 90 seconds",
  tagline: "One shift as a mamak anne. Listen, brew, serve.",
  steps3: ["👂 Listen", "🫗 Brew", "🪑 Serve"],
  start: "▶ Start shift",
  howTo: "How to play & mamak dictionary",
  howToItems: [
    "☕ 4 steps: cup (hot/iced) → powder → milk → sugar.",
    "🥛 O = no milk · C = evaporated milk.",
    "🍬 Less = less sweet · Kosong = no sugar.",
    "👨‍👩‍👧 One table can order several drinks. Serve them one by one.",
    "🤔 Forgot? Ask again, max 2 times. Customers get annoyed!",
    "🍵 Teh tarik = hot + teh + milk + normal sugar.",
  ],
  yourBest: "🏆 Your best:",
  challenge: (amount, title) => `Your friend made ${amount} (${title}). Can you beat it?`,
  loading: "Opening shop...",
  shiftOver: "Shift over!",
  stats: { served: "Served", wrong: "Wrong", walkouts: "Left", streak: "Streak" },
  newRecord: "New record!",
  namePlaceholder: "Your name",
  save: "Save",
  nameTooShort: "Name needs 2+ letters",
  zeroScore: "Serve at least one drink to enter the leaderboard",
  savedRank: (n) => `You're #${n} this week!`,
  savedRankToday: (n) => `You're #${n} today!`,
  saved: "Score saved!",
  saveFailed: "Couldn't save",
  challengeFriends: "Challenge friends",
  playAgain: "▶ Play again",
  copied: "Link copied. Paste it on Threads!",
  shareText: (amount, emoji, title) => `I made ${amount} in one shift at Anne Maju ${emoji} (${title}). Can you beat me?`,
  board: "🏆 Leaderboard",
  week: "This week",
  all: "All time",
  boardLoading: "Loading...",
  boardEmpty: "No champions yet. Be the first!",
  rotate: "Rotate your phone",
  rotateSub: "This game plays in landscape",
  mute: "Mute",
  unmute: "Unmute",
  discard: "Throw away drink",
  steps: { temp: "Cup", base: "Powder", milk: "Milk", sugar: "Sugar" },
  values: {
    panas: "Hot",
    ais: "Iced",
    teh: "Teh",
    kopi: "Kopi",
    milo: "Milo",
    nescafe: "Nescafe",
    susu: "Milk",
    c: "C",
    o: "O",
    biasa: "Normal",
    kurang: "Less",
    kosong: "None",
  },
  labels: {
    panas: "HOT",
    ais: "ICED",
    teh: "TEH",
    kopi: "KOPI",
    milo: "MILO",
    nescafe: "NESCAFE",
    susu: "MILK",
    c: "C",
    o: "O",
    biasa: "NORMAL",
    kurang: "LESS",
    kosong: "NONE",
  },
  ready: "READY! TAP CUSTOMER",
  serveHere: "Serve",
  askAgain: (left) => `Forgot? ${left}x`,
  noMoreAsks: "Asked twice",
  annoyedAsk: "Listen properly this time!",
  refusedAsk: "Told you twice already!",
  ranks: ["Fresh Hire", "Amateur Brewer", "Senior Anne", "Mamak Boss", "24-Hour Tarik Legend"],
  happy: ["Best lah boss!", "Power la anne!", "Steady!", "Sedap, thanks!", "Now that's right!"],
  wrong: ["Aiyo, this is not my order!", "Eh boss, wrong one!", "I said something else la...", "Whose drink is this?", "Haih, not listening ah?"],
  leave: ["Too slow, I'm going!", "Never mind, next shop.", "Didn't even take my order..."],
  calls: ["Anne", "Boss", "Bro", "Uncle", "Macha"],
  ends: [" please!", ", fast ah!", ", thanks!", " boss!", "!"],
  numbers: ["", "one", "two", "three", "four"],
  sugarKurang: "less sweet",
  sugarKosong: "no sugar",
  paused: "Paused",
  pause: "Pause",
  resume: "▶ Resume",
  restart: "↻ Restart",
  quit: "← Back to Kuala Lepak",
  language: "Language",
  sound: "Sound",
  practice: "Practice",
  tutorialTitle: "Quick practice!",
  tutorialIntro: "Your first customer. No timer, just follow along.",
  hintStep: (want, label) => `They want ${want} → tap ${label}`,
  hintServe: "Done! Tap the customer to serve 👉",
  hintWrongCup: "That doesn't match the order. Tap 🗑️ and try again",
  tutorialDoneTitle: "Nice one! 🎉",
  tutorialDoneBody: "Now the real shift: 90 seconds, lots of customers, some in groups.",
  startReal: "▶ Start the real shift",
  skipTutorial: "Skip practice",
  slip: "📝 Slip",
  slipHint: "Tap an order to write it on your slip",
  slipTable: (n) => `Table ${n}`,
  explain: (parts) => `Wanted ${parts.join(", ")}!`,
  notThis: (want, got) => `${want}, not ${got}`,
  fieldWords: { panas: "hot", ais: "iced", teh: "teh", kopi: "kopi", milo: "milo", nescafe: "nescafe", susu: "milk", c: "C", o: "O", biasa: "normal sugar", kurang: "less sweet", kosong: "no sugar" },
  combo: (n) => (n >= 10 ? `🔥 x${n} Legend!` : n >= 5 ? `🔥 x${n} Steady!` : `🔥 x${n} Power!`),
  sales: "Sales",
  tips: "Tips",
  wasted: "Wasted",
  nextRank: (amount, title) => `${amount} more to become ${title}`,
  topRank: "You've reached the top rank! 👑",
  unlockedNew: "🔓 New on the menu:",
  unlockNames: { nescafe: "Nescafe & no-sugar orders", c: "C (evaporated milk)" },
  nextUnlock: (amount, name) => `Earn ${amount} more (all shifts) to unlock ${name}`,
  outfitTitle: "Anne's style",
  outfitNew: "👕 New outfit unlocked!",
  dailyStart: "📅 Today's Shift",
  dailySub: "Same customers for everyone. Who's fastest?",
  today: "Today",
  dailyBadge: "📅 Today's shift",
};

const STRINGS: Record<Lang, Strings> = { ms, en };
