import type { Lang } from "@/shared/lang";

const ms = {
  brand: "Hidup, kerja, lepak.",
  hintDesktop: "WASD jalan · Q/R pusing kamera · klik pergi",
  hintTouch: "Kiri: jalan · Kanan: pusing kamera · tap pergi",
  goTo: (name: string) => `Jalan ke ${name} untuk main`,
  enter: "Masuk",
  leave: "Keluar",
  inside: "Dalam bangunan",
  insideDefault: "Senyap sikit. Tengok sekeliling, lepas tu keluar.",
  play: "Main",
  soon: "Akan datang",
  soonBody: "Game ni tengah dibina. Nantikan!",
  you: "KAU",
  loading: "Bandar tengah dibuka...",
  tagline: "Kau baru pindah ke Kuala Lepak. Cari kerja, kenal orang, dan jangan lupa usap Oyen.",
  startCta: "▶ Mula jalan",
  startKey: "atau tekan Enter",
  keysWalk: "jalan",
  keysEnter: "masuk / mula",
  keysClick: "klik untuk pergi",
  madeIn: "Dibuat dengan ❤️ di Malaysia",
  controlsDesktop: "🎮 WASD / anak panah · klik untuk jalan · Enter untuk masuk",
  controlsTouch: "🎮 Joystick atau tap untuk jalan",
  petCat: (name: string) => `Usap ${name}`,
  catLoves: (name: string, n: number) => `${name} suka kau! ❤️ · ${n} kali usap kucing`,
  wallet: "Dompet",
  clock: "Masa",
  periodPagi: "Pagi",
  periodTengah: "Tengah hari",
  periodPetang: "Petang",
  periodMalam: "Malam",
  level: (n: number) => `Lv ${n}`,
  phone: "Telefon",
  phoneSoon: "Telefon datang fasa seterusnya. Tunggu je!",
  paid: (job: string, amount: string) => `${job} · +${amount} masuk dompet`,
  close: "Tutup",
  appMesej: "Mesej",
  appTugasan: "GIG",
  appProfil: "Profil",
  appDompet: "Dompet",
  appTetapan: "Tetapan",
  appKerja: "Kerja",
  appPeta: "Peta",
  inboxEmpty: "Tiada mesej lagi. Kak Yati akan text kau.",
  markRead: "Dibaca",
  acceptTask: "Terima",
  acceptFailed: "Belum boleh terima — siap GIG sebelum ni dulu.",
  taskActive: "GIG aktif",
  taskDone: "Dah siap",
  activeTasks: "Aktif",
  doneTasks: "Siap",
  noTasks: "Tiada GIG aktif. Buka Mesej.",
  profilLevel: "Level",
  profilXp: "XP ke level seterusnya",
  profilGigs: "GIG",
  profilGigsActive: "Aktif",
  profilGigsDone: "Siap",
  pinned: "dipin",
  noLedger: "Belum ada transaksi.",
  cloudAccount: "Akaun cloud",
  register: "Daftar",
  login: "Log masuk",
  logout: "Log keluar",
  welcomeBack: (name: string) => `Selamat kembali, @${name}!`,
  tutTitle: "Selamat datang!",
  tutWelcome: (name: string) => `Hai @${name} — kau baru pindah ke Kuala Lepak.`,
  tutMove: "Jalan dengan WASD (atau joystick kiri kat telefon).",
  tutLook: "Pusing kamera dengan Q/R (atau pad kanan).",
  tutPhone: "Buka Telefon untuk Mesej, GIG & Profil.",
  tutWorld: "Sembang dengan orang, usap kucing, naik bas / LRT.",
  tutNext: "Seterusnya",
  tutSkip: "Langkau",
  tutStart: "Mula jalan!",
  authGateTitle: "Masuk Kuala Lepak",
  authGateBody: "Pilih nama kau + PIN 6 digit. Baru? Auto daftar. Dah ada? Auto masuk.",
  authUserLabel: "Username",
  authUserPlaceholder: "nama kau",
  authPinLabel: "PIN rahsia",
  authPinPlaceholder: "PIN · 6 digit",
  authGo: "Masuk!",
  authHint: "Nama 5–20 huruf/nombor/_ · PIN 6 digit",
  talk: (name: string) => `Sembang dengan ${name}`,
  buy: (label: string, price: string) => `Beli ${label} ${price}`,
  give: (label: string, name: string) => `Hantar ${label} kat ${name}`,
  bought: (label: string) => `Dah beli ${label}`,
  gave: (label: string, name: string) => `Dah hantar ${label} kat ${name}`,
  tapContinue: "Tap untuk teruskan",
  busSoon: "Bas ke Taman Ceria belum ready. Nanti!",
  needMoney: "Duit tak cukup",
  busToTaman: "Naik bas → Taman Ceria",
  busToPusat: "Naik bas → Pusat Lepak",
  busToKlcc: "Naik bas → KLCC",
  busToMenara: "Naik bas → Menara Lepak",
  busToTlx: "Naik bas → TLX",
  busToBintik: "Naik bas → Bukit Bintik",
  busToJalan: "Naik bas → Bukit Jalan",
  busToKampung: "Naik bas → Kampung Lepak",
  busToPasar: "Naik bas → Pasar Besar",
  busToPetaling: "Naik bas → Petaling Lane",
  busToSentral: "Naik bas → Sentral Lepak",
  busBoardTitle: "Bas ke mana?",
  busBoardHint: "Pilih laluan RapidLepak",
  busOpenBoard: "Bas ke…",
  busRiding: "Dalam perjalanan…",
  busArrived: "Hampir sampai…",
  busFare: "RM1.00",
  busReturnEta: (route: string, eta: string) => `${route} → Pusat · ${eta}`,
  lrtEnter: "Masuk stesen LRT",
  lrtBoardTitle: "LRT Laluan Kelana",
  lrtBoardHint: "Pilih stesen — RM1.20",
  lrtArriving: "Kereta api tiba…",
  lrtRiding: "Dalam perjalanan…",
  lrtFare: "RM1.20",
  railEnter: "Naik tren",
  railBoardHint: "Pilih stesen",
  railArriving: "Kereta api tiba…",
  railRiding: "Dalam perjalanan…",
  taxiArriving: "Teksi datang…",
  taxiRiding: "Dalam teksi…",
  taxiFare: "RM3.50",
  taxiTitle: "Teksi Kumar",
  taxiLocked: "Jumpa Kumar kat Sentral untuk unlock teksi.",
  petaTitle: "Peta",
  petaHint: "Stesen yang kau dah jumpa + teksi (bila unlock)",
  petaStations: "Stesen",
  petaTaxi: "Teksi",
  petaNeedDiscover: "Jalan ke stesen dulu untuk unlock fast travel.",
  petaOpenMap: "Buka peta penuh",

  sitSofa: "Duduk kat sofa",
  satHome: "Rehat. Selamat sampai rumah.",
  mapTitle: "Peta Kuala Lepak",
  mapHint: "Seret untuk pan · tap untuk set wayfinder",
  mapPin: "Pin kau",
  mapClearPin: "Buang pin",
};

type Strings = typeof ms;

const en: Strings = {
  brand: "Live, work, lepak.",
  hintDesktop: "WASD walk · Q/R turn camera · click to go",
  hintTouch: "Left: walk · Right: turn camera · tap to go",
  goTo: (name) => `Walk to ${name} to play`,
  enter: "Enter",
  leave: "Leave",
  inside: "Inside",
  insideDefault: "Quiet for now. Look around, then head out.",
  play: "Play",
  soon: "Coming soon",
  soonBody: "This game is being built. Stay tuned!",
  you: "YOU",
  loading: "Opening the city...",
  tagline: "You just moved to Kuala Lepak. Find work, make friends, and don't forget to pet Oyen.",
  startCta: "▶ Start exploring",
  startKey: "or press Enter",
  keysWalk: "walk",
  keysEnter: "enter / start",
  keysClick: "click to go",
  madeIn: "Made with ❤️ in Malaysia",
  controlsDesktop: "🎮 WASD / arrows · click to walk · Enter to go in",
  controlsTouch: "🎮 Joystick or tap to walk",
  petCat: (name) => `Pet ${name}`,
  catLoves: (name, n) => `${name} loves you! ❤️ · ${n} ${n === 1 ? "cat petted" : "cats petted"}`,
  wallet: "Wallet",
  clock: "Time",
  periodPagi: "Morning",
  periodTengah: "Midday",
  periodPetang: "Evening",
  periodMalam: "Night",
  level: (n) => `Lv ${n}`,
  phone: "Phone",
  phoneSoon: "The phone lands in the next phase. Stay tuned!",
  paid: (job, amount) => `${job} · +${amount} added to your wallet`,
  close: "Close",
  appMesej: "Messages",
  appTugasan: "GIGs",
  appProfil: "Profile",
  appDompet: "Wallet",
  appTetapan: "Settings",
  appKerja: "Jobs",
  appPeta: "Map",
  inboxEmpty: "No messages yet. Kak Yati will text you.",
  markRead: "Read",
  acceptTask: "Accept",
  acceptFailed: "Can't accept yet — finish the earlier GIG first.",
  taskActive: "Active GIG",
  taskDone: "Done",
  activeTasks: "Active",
  doneTasks: "Done",
  noTasks: "No active GIGs. Open Messages.",
  profilLevel: "Level",
  profilXp: "XP to next level",
  profilGigs: "GIGs",
  profilGigsActive: "Active",
  profilGigsDone: "Done",
  pinned: "pinned",
  noLedger: "No transactions yet.",
  cloudAccount: "Cloud account",
  register: "Register",
  login: "Log in",
  logout: "Log out",
  welcomeBack: (name) => `Welcome back, @${name}!`,
  tutTitle: "Welcome!",
  tutWelcome: (name) => `Hey @${name} — you just moved to Kuala Lepak.`,
  tutMove: "Walk with WASD (or the left stick on phone).",
  tutLook: "Turn the camera with Q/R (or the right look pad).",
  tutPhone: "Open Phone for Messages, GIGs & Profile.",
  tutWorld: "Chat with people, pet cats, ride the bus / LRT.",
  tutNext: "Next",
  tutSkip: "Skip",
  tutStart: "Let's go!",
  authGateTitle: "Enter Kuala Lepak",
  authGateBody: "Pick a username + 6-digit PIN. New? Auto signup. Returning? Auto login.",
  authUserLabel: "Username",
  authUserPlaceholder: "your name",
  authPinLabel: "Secret PIN",
  authPinPlaceholder: "PIN · 6 digits",
  authGo: "Go!",
  authHint: "Username 5–20 letters/numbers/_ · 6-digit PIN",
  talk: (name) => `Chat with ${name}`,
  buy: (label, price) => `Buy ${label} ${price}`,
  give: (label, name) => `Give ${label} to ${name}`,
  bought: (label) => `Bought ${label}`,
  gave: (label, name) => `Gave ${label} to ${name}`,
  tapContinue: "Tap to continue",
  busSoon: "Bus to Taman Ceria isn't ready yet.",
  needMoney: "Not enough money",
  busToTaman: "Bus → Taman Ceria",
  busToPusat: "Bus → Pusat Lepak",
  busToKlcc: "Bus → KLCC",
  busToMenara: "Bus → Menara Lepak",
  busToTlx: "Bus → TLX",
  busToBintik: "Bus → Bukit Bintik",
  busToJalan: "Bus → Bukit Jalan",
  busToKampung: "Bus → Kampung Lepak",
  busToPasar: "Bus → Pasar Besar",
  busToPetaling: "Bus → Petaling Lane",
  busToSentral: "Bus → Sentral Lepak",
  busBoardTitle: "Where to?",
  busBoardHint: "Pick a RapidLepak route",
  busOpenBoard: "Bus to…",
  busRiding: "On the way…",
  busArrived: "Almost there…",
  busFare: "RM1.00",
  busReturnEta: (route, eta) => `${route} → Pusat · ${eta}`,
  lrtEnter: "Enter LRT station",
  lrtBoardTitle: "LRT Laluan Kelana",
  lrtBoardHint: "Pick a station — RM1.20",
  lrtArriving: "Train arriving…",
  lrtRiding: "On the way…",
  lrtFare: "RM1.20",
  railEnter: "Board train",
  railBoardHint: "Pick a station",
  railArriving: "Train arriving…",
  railRiding: "On the way…",
  taxiArriving: "Taxi arriving…",
  taxiRiding: "In the taxi…",
  taxiFare: "RM3.50",
  taxiTitle: "Kumar's taxi",
  taxiLocked: "Meet Kumar at Sentral to unlock taxis.",
  petaTitle: "Map",
  petaHint: "Stations you've found + taxi (when unlocked)",
  petaStations: "Stations",
  petaTaxi: "Taxi",
  petaNeedDiscover: "Visit a station first to unlock fast travel.",
  petaOpenMap: "Open full map",
  sitSofa: "Sit on the sofa",
  satHome: "Ahh. Home sweet home.",
  mapTitle: "Kuala Lepak map",
  mapHint: "Drag to pan · tap to set a wayfinder",
  mapPin: "Your pin",
  mapClearPin: "Clear pin",
};

export const HUB_STRINGS: Record<Lang, Strings> = { ms, en };
